### PR TITLE
Fix valid domain regex

### LINKED ISSUE #56: localhost is not a valid domain name
On the latest version (using `devcert-cli`):

```
devcert generate localhost
Error: "localhost" is not a valid domain name.
```

same for `127.0.0.1` and my local ip

### PR DESCRIPTION
**Pull request by stramel**
Fixes #56 

Based on https://gist.github.com/dperini/729294

Stripped the following checks from the above gist regex:

- protocol (http, ftp)
- short syntax (//)
- basic auth (user:pass)
- requirement for TLD (\. made optional)
- port number (:port)
- resource path (/path, #resource-path)

Should now work for IPs, `localhost`, and valid domains

**UPDATE:** Since the generated certificates don't support IP addresses, I reverted the change and just simply modified the Regex to handle `localhost` and make it case-insensitive.

/cc @Js-Brecht

### CODE REVIEW

**Comment by Js-Brecht** [comment]
It doesn't seem to match any IP addresses.  Of course, the generated certificates also don't support IP addresses, so maybe it's a good thing for it to fail early when an IP address is provided as hostname

/cc @zetlen

**Comment by stramel** [comment]
@Js-Brecht If we don't want to match IP addresses, we can probably just add the localhost support to the existing regex?

**Comment by stramel** [comment]
Could probably switch `/(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.?)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]/i` would probably work. Also, not sure if `0-9` should be in that first group?

**Comment by Js-Brecht** [comment]
I guess I did 😆.  I think it will need to be done eventually, so maybe it will be good to have something on standby.  Currently, though, the certificates generated do not use IP SANs.  Didn't really think about that when I said it.

> Could probably switch the regex to `/(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.?)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]/i` and would probably work. Also, not sure if `0-9` should be in that first group?

Since, technically, domain names can have numbers in them, it makes sense to keep the `0-9`.

That regexp works, but it also matches on just the first octet of an IP address like `127.0.0.1`, since the final test, `[a-z0-9][a-z0-9-]{0,61}[a-z0-9]`, requires a minimum of two characters in the last position.  So IP addresses _will_ pass the domain name check, but they won't actually be validated.

Maybe there should be a separate regex to match IP addresses, so that they can be matched prior to domain name validation?  Then a friendly error could be generated to indicate that IP addresses aren't supported at the moment?  Later, when they are supported, the condition could be changed to accept the IP, and a monolithic regular expression wouldn't have to be picked apart to ensure compatibility.

**Comment by stramel** [comment]
@Js-Brecht The regex no longer matches the octets of any IP. I also added a quick IPv4 regex and check that throws an error if an IP is provided.

File: src/index.ts [hunk 1]
```diff
@@ -66,6 +67,8 @@ type IReturnData<O extends Options = {}> = (IDomainData) & (IReturnCa<O>) & (IRe
  * as { caPath: string }
  */
 export async function certificateFor<O extends Options>(domain: string, options: O = {} as O): Promise<IReturnData<O>> {
+  if (VALID_IP.test(domain)) {
+    throw new Error('IP addresses are not supported currently');
```
Comment (Js-Brecht) [inline src/index.ts:71]: I think a `}` was missed here
```suggestion
  if (VALID_IP.test(domain)) {
    throw new Error('IP addresses are not supported currently');
  }
```

**Comment by stramel** [comment]
Doh! Thanks, just did it quickly with the inline editor.

**Comment by stramel** [comment]
Ping @zetlen @davewasmer

**Comment by JustFly1984** [comment]
Is there any movement on the issue?

**Comment by stramel** [comment]
@Js-Brecht Is there any way to move this along? This is rather inconvenient to deal with at the moment.

**Comment by Js-Brecht** [comment]
@stramel unfortunately, I don't have write access.

@zetlen I hate to bother you; I'm sure you're busy.  This issue really is causing a lot of grief for Gatsby users, though.  Would you mind taking a look at this PR so we can resolve these problems?

**Comment by zetlen** [comment]
I'm so sorry, folks! @Js-Brecht I have been on vacation for a week, but I'll look at this right now.

**Comment by zetlen** [comment]
Confirmed locally, this fixes the issue.

**Comment by Js-Brecht** [comment]
Welcome back @zetlen!  Thanks for the merge :rocket:; I'm sure everybody will be glad.

**Comment by zetlen** [comment]
@stramel @Js-Brecht Published `v1.1.2` to NPM.

**Comment by stramel** [comment]
Thank you @zetlen! Sorry for bugging you on vacation!

**Comment by JustFly1984** [comment]
Ping @zetlen @davewasmer
